
#Screen Things
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#Asteroid Things
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#Colour Things
BLACK_COLOUR = (0,0,0)
WHITE_COLOUR = (255,255,255)

#Player Things
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200